name: Python 3.10.5
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
      - name: Switch to Project Directory
        run: |
          cd example_project
      - name: Install Project Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r example_project/requirements.txt
      - name: Check for Python Syntax Errors w/flake8
        run: |
          pip install flake8
          # Fail the build if there are Python syntax errors or undefined names
          flake8 . --count --statistics --show-source --select=E9,F63,F7,F82 
      - name: Check for Python Syntax Warnings w/flake8
        run: |
          # exit-zero disables 
          flake8 . --count --statistics --exit-zero --select=E712,F401
      - name: Run Behave Tests
        run: |
          pip install behave
          cd example_project
          behave -o results.txt
      - name: Upload Behave Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: behave_results
          path: |
            example_project/results.txt