name: Python Version Complex Matrix
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10.5']
        exclude:
          - os: ubuntu-latest
            python-version: '3.9'
          - os: windows-latest
            python-version: '3.10.5'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Behave Tests
        uses: cryptic-wizard/run-behave-tests@v0.2.0
        with:
          requirements-name: example_project/requirements.txt
          test-path: example_project
          test-output-name: ${{ matrix.os }}-${{ matrix.python-version }}.txt
      - name: Upload Behave Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: behave_results
          path: |
            example_project/${{ matrix.os }}-${{ matrix.python-version }}.txt