name: Python 3.10.5 Minimal
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
      - name: Run Behave Tests
        uses: cryptic-wizard/run-behave-tests@v0.1.0-beta4
        with:
          requirements-name: example_project/requirements.txt
          test-path: example_project
      - name: Upload Behave Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: behave_results
          path: |
            example_project/results.txt